### ISSUE TITLE
Add timers for stm32

### ISSUE THREAD

**Issue by xoviat** [akiles/embassy#38]
The current plan is this:

1. Wait until stm32-rs/stm32f4xx-hal#228 is merged.
2. Wait submit a subsequent PR that includes interrupts.
3. Submit a PR to embassy that wraps the HAL and implements the timer interface.

**Comment by Dirbaio** [comment]
The stm32's RTC is for human time (y/m/d h:m:s). Embassy's Clock/Alarm traits want a *monotonic* clock, one that always ticks up at a fixed rate and never jump back or forward. Doing so would break the executor.

Maybe Clock/Alarm can be implemented with TIMER peripherals instead? I'm not familiar with the stm32 hardware at all, maybe there's a way to clock a TIMER from the 32khz crystal if any, in which case it'd be low power.

**Comment by Dirbaio** [comment]
Done in #49
