### ISSUE TITLE
nrf-softdevice faults when used with embassy_nrf::Gpiote

### ISSUE THREAD

**Issue by fnafnio** [akiles/embassy#42]
As the title says, when using embassy_nrf::Gpiote together with nrf-softdevice, the nrf-softdevice (S140  7.2.0)
an explicit panic occurs, in this case with

`0.001253 ERROR panicked at 'fault_handler 4097 191576 0'`

I still have to investigate this further (and throw together a minimal example), but I assume it has something to do with NVIC access or critical sections.

If someone could point out where to look further it would be much appreciated

Edit: 
I created a button handler task which awaits a pin using GPIOTE port interrupt, then polls the desired pin every 5ms (timer provided by embassy::time) to debounce

**Comment by Dirbaio** [comment]
Softdevice+GPIOTE works fine in my project, I think there's something else going on here.

When you get a softdevice fault, check the NRF_FAULT_ID. In this case it's NRF_FAULT_ID_APP_MEMACC. Docs on it say this:

    Application invalid memory access. The info parameter will contain 0x00000000,
    in case of SoftDevice RAM access violation. In case of SoftDevice peripheral
    register violation the info parameter will contain the sub-region number of
    PREGION[0], on whose address range the disallowed write access caused the
    memory access fault.

The PC value points to somewhere in your code where presumably the bad access happened. I'd check what's in there and go from there...
