### ISSUE TITLE
I2C traits

### ISSUE THREAD

**Issue by eupn** [akiles/embassy#51]
I'm extensively using I2C in my project together with `embassy` and it would be nice to have an I2C interface trait to implement for a particular chip (stm32wb55 in my case).

**Comment by eupn** [comment]
I ended up using [async-embedded-traits](https://github.com/Disasm/async-embedded-traits) for this. It might be a good idea to have these traits implemented in `embassy` to have a more coherent ecosystem.

**Comment by Dirbaio** [comment]
Interesting!

The main difference I see is they take `&mut self` instead of `Pin<&mut Self>`. Pin is necessary so the driver can own and handle interrupts.

Do you have pointers to `async-embedded-traits` implementations? How do they handle interrupts?

**Comment by eupn** [comment]
@Dirbaio I have I2C implemented [here](https://github.com/eupn/embassy/blob/add-stm32wb55/embassy-stm32wb55/src/i2c.rs). Though it seems to work fine, I'm not sure about its soundness.
